### ISSUE TITLE
Complete the employee on-boarding process

### ISSUE THREAD

**Issue by m1yag1** [openstax/quality-assurance-meta#4]
Malar needs to complete the on-boarding process. 

# On-boarding Checklist
- [x] Fill out I-9
- [x] Pick out equipment and send to oxadmin@rice.edu
- [x] Activate NetID https://kb.rice.edu/page.php?id=58397
- [x] Pick a New Hire orientation day http://people.rice.edu/learn-grow/new-employee-guide/new-hire-orientation/
- [x] Get Rice and garage parking card
- [x] Review the OpenStax new hire guide: https://docs.google.com/document/d/1dxBzcbJs8HwUuc8PVMSOoO8ABQHZ3eOrrLh_zLeHkus/edit
- [x] FERPA Training https://registrar.rice.edu/ferpa-training-assessment
- [ ] ~Sexual harassment training~
- [x] Get Email and calendar setup on your cell phone
- [x] Login to google with your NetID so you can see your calendar
- [x] Accept Slack account invitation
- [x] Get a GitHub account
- [x] Get a ZenHub account (Login with your GitHub account)
- [x] Get a Trello account
- [x] TestRail account
- [x] Send Mike info to do your announcement
- [x] Schedule weekly 1:1 with Mike

**Comment by Malar-Natarajan** [comment]
Status update on new hire checklist:

Get Email and calendar setup on your cell phone – To be done next week

Fill out I-9 - Completed
 Pick out equipment and send to oxadmin@rice.edu - Completed
 Activate NetID  - Completed
 Pick a New Hire orientation day  - Completed
 Get Rice and garage parking card – Completed 
 Review the OpenStax new hire guide - Completed
 FERPA Training - Completed
 Sexual harassment training- Not Applicable
 Login to google with your NetID so you can see your calendar - Completed
 Accept Slack account invitation - Completed
 Get a GitHub account - Completed
 Get a ZenHub account - Completed
 Get a Trello account - Completed
 TestRail account - Completed

**Comment by m1yag1** [comment]
🎉 yay! we are basically done except for the orientation 🍰

**Comment by m1yag1** [comment]
oh wait I added one more thing. You should be able to edit the issue directly. Clicking on the box should check it for you.

**Comment by Malar-Natarajan** [comment]
Oh..that last one...i will do it.

**Comment by m1yag1** [comment]
This is pretty much done.
