### ISSUE TITLE
QA Request: Method to copy data between servers for test collections.

### ISSUE THREAD

**Issue by Stackblocks** [openstax/quality-assurance-meta#77]
As a QA Analyst I want to be able to copy test data from one server to another for test purposes without having to log in to both servers and copy modules over by hand.

Currently we have the content-copy-tool, but it is unwieldy and getting progressively more unwieldy over time. As a bare-bones function I would like something to copy over a specified set of modules, and output a list of module numbers and titles so I can create a collection by hand afterwards.

**Comment by kerwinso** [comment]
This would have wide-ranging benefits beyond just for QA, at least for as long as we are stuck with legacy.

**Comment by m1yag1** [comment]
First iteration on this has been completed.
