### ISSUE TITLE
QA Request: Improve URL Commands Tool

### ISSUE THREAD

**Issue by Stackblocks** [openstax/quality-assurance-meta#78]
Baking / monitoring the bake status of a suite of books for wide-band testing or when we're developing a new suite of titles requires a lot of url swapping.

For the business series I would `enqueue` five books, monitor the `query_ptool` report while I wait for them to generate a PDF, and then download all the PDFs from the server. This meant visiting ~three url commands pages per book

It would be ideal if we could run multiple of these in parallel without having to have fifteen tabs open across five windows tracking all of this.

**Comment by m1yag1** [comment]
@Stackblocks please tryout the new tool and see how it works for you. If you encounter any issues please create them on the repo.

https://github.com/openstax/krunk-copy
https://pypi.org/project/krunk-copy/
