### ISSUE TITLE
Add sensitive information required for testing into Box QA Vault

### ISSUE THREAD

**Issue by m1yag1** [openstax/quality-assurance-meta#84]
Please login to https://rice.app.box.com/ and look for the `QA Vault` note. Add in any accounts that you use for testing. We should have a single place where these exist so whenever someone is out or they get borked and we need to recreate them we have the password somewhere easy to find ;). 

If for some reason you can't share globally place the service name and a line saying "Ask [so and so]". It's possible we need to get a personal token or something from a Dev. 

## Acceptance criteria

- [x] Alan is done
- [x] Greg is done
- [x] Malar is done
- [x] Mike is done
- [x] Mulich is done

**Comment by pumazi** [comment]
I don't believe I have anything to add at this time. I have logged into the service and looked at the doc. ✅
