### ISSUE TITLE
Harden Accounts and Web tests

### ISSUE THREAD

**Issue by gregfitch** [openstax/quality-assurance-meta#98]
Description
Stabilize the Accounts and openstax.org automation test scripts so they may provide value to developers

Rationale
Test script failures and flaky tests limit the utility of the automated functional tests for OpenStax Accounts and OpenStax Web (openstax.org) outside of QA, especially as OpenStax moves toward continuous delivery.

Key Results
Determine current 'flaky' tests to build a test set for use with CI and headless Chrome
Minimize generalized errors (<3 per run) when using Chrome
Minimize generalized errors (<3 per run) when using Firefox
Minimize generalized errors (<3 per run) when using Safari

**Comment by m1yag1** [comment]
@gregfitch
The general practice now is that Epics are KDs. Please format like the other KDs using Rationale and Description, and Key Results. How do you know that `Harden Accounts and Openstax.org tests` is successful?

## Reference for KD format
https://github.com/openstax/quality-assurance-meta/issues/92

## Reference for Value based Key Results
https://felipecastro.com/en/okr/success-criteria-types-key-results/

**Comment by gregfitch** [comment]
[https://app.zenhub.com/files/133541702/7475a5bd-29c6-4757-8e12-a776a0554b4b/download](https://app.zenhub.com/files/133541702/7475a5bd-29c6-4757-8e12-a776a0554b4b/download)

**Comment by m1yag1** [comment]
Awesome, so now we have that before report and at the end of the quarter those tests would not be failing anymore... or some percentage. that's really great!

**Comment by m1yag1** [comment]
@gregfitch Thanks for updating the card. Did you have a similar KD about the tutor work?

**Comment by m1yag1** [comment]
pinging @gregfitch ☝️

**Comment by gregfitch** [comment]
[https://app.zenhub.com/files/133541702/e669f27d-9a17-418e-8190-060f0f11141b/download](https://app.zenhub.com/files/133541702/e669f27d-9a17-418e-8190-060f0f11141b/download)
